dagr2/dagr/urls.py
from django.urls import path, re_path
from . import views

app_name = 'dagr'

urlpatterns = [
    #path(r'', views.index, name='index'),
    re_path(r'^$', views.add_manually, name='add'),
    re_path(r'^message/(?P<message>\w+)/$', views.message, name='message'),
    re_path(r'^add/manually/$', views.add_manually, name='add_manually'),
    re_path(r'^add/url/$', views.add_url, name='add_url'),
    re_path(r'^add/file/$', views.add_file, name='add_file'),
    re_path(r'^add/category/$', views.add_category, name="add_category"),
    re_path(r'^add/keyword/$', views.add_keyword, name="add_keyword"),


    #re_path(r'^queries/$', views.queries, name='dagr_queries'),
    re_path(r'^metadata/$', views.metadata, name='metadata'),
    re_path(r'^reach/$', views.reach, name='reach'),
    re_path(r'^time/(?P<rang>\w+)/$', views.time_range, name='time-range'),
    re_path(r'^time/$', views.time, name='time'),
    re_path(r'^family/(?P<descendant>\w+)/$', views.descendant, name='descendant'),
    re_path(r'^update/(?P<guid>\d+)/$', views.update_dagr, name='update_dagr'),
    re_path(r'^delete/(?P<guid>\d+)/$', views.delete_dagr, name='delete_dagr'),

]

dagr2/dagr/forms.py
from django import forms
from .models import Dagr, Category, Keyword
from multiupload.fields import MultiFileField
from datetimewidget.widgets import DateTimeWidget


dateTimeOptions = {
    'format': 'yyyy-mm-dd HH:ii',
    'autoclose': True,
    'showMeridian' : False
    }

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['categoryID', 'categoryName']
        labels = {
            'categoryName':'Create Category'
        }

class KeywordForm(forms.ModelForm):
    class Meta:
        model = Keyword
        fields = ['keywordID', 'name']
        labels = {
            'name':'Create Keyword'
        }

class DagrForm(forms.ModelForm):
    class Meta:
        model = Dagr
        fields = ['Guid','Location','RealName','AssignedName',
         'Size', 'Type','CategoryID','Author','LastModified', 'DateCreated',]
        widgets = {
        'LastModified':DateTimeWidget(options=dateTimeOptions, usel10n = True),
        'DateCreated':DateTimeWidget(options=dateTimeOptions, usel10n = True),
        'Location': forms.TextInput(attrs={'class':'form-control'}),
        'RealName':  forms.TextInput(attrs={'class':'form-control'}),
        "AssignedName":  forms.TextInput(attrs={'class':'form-control'}),
        "Size": forms.NumberInput(attrs={'class':'form-control'}),
        "Type":  forms.TextInput(attrs={'class':'form-control'}),
        "Category": forms.Select(attrs={'class':'form-control'}),
        "Author":  forms.TextInput(attrs={'class':'form-control'}),
        }
        labels = {
        'LastModified': 'Date Last Modified',
        'DateCreated': 'Date Created',
        'CategoryID': 'Category',
        'RealName': 'Real Name',
        'AssignedName': 'Assigned Name',
        }

        def __init__(self, *args, **kwargs):
            # first call parent's constructor
            super(DagrForm, self).__init__(*args, **kwargs)
            # there's a `fields` property now
            self.fields['Location'].required = False
            self.fields['RealName'].required = False
            self.fields['LastModified'].required = False
            self.fields['CategoryID'].required = False
            self.fields['AssignedName'].required = False
            self.fields['Size'].required = False
            self.fields['Type'].required = False
            self.fields['DateCreated'].required = False
            self.fields['Author'].required = False

class HtmlParserForm(forms.Form):
    url =  forms.URLField(label="Enter Wesbite URL", max_length=300,
    widget=forms.TextInput(attrs={'class':'form-control'}))
    #depth = forms.IntegerField(label="Depth", required=True, widget=forms.TextInput(attrs={'class':'form-control'}))

class UploadForm(forms.Form):
    documents = MultiFileField(min_num=1, max_num=100, max_file_size=1024000*1024000*500)
    categorys = Category.objects.all()
    category = forms.ModelChoiceField(queryset=categorys,label="Category",required=False,
    widget=forms.Select(attrs={'class':'form-control'}))

class MetaDataForm(forms.Form):
    author = forms.CharField(label="Author",required=False, widget=forms.TextInput(attrs={'class':'form-control'}))
    size = forms.DecimalField(label="Size",required=False,  widget=forms.NumberInput(attrs={'class':'form-control'}))
    typ = forms.CharField(label="Type",required=False,  widget=forms.TextInput(attrs={'class':'form-control'}))
    name = forms.CharField(label="Name", required=False,  widget=forms.TextInput(attrs={'class':'form-control'}))
    location = forms.CharField(label="Location", required=False,  widget=forms.TextInput(attrs={'class':'form-control'}))

    categorys = Category.objects.all()
    category = forms.ModelMultipleChoiceField(queryset=categorys,label="Category",required=False,
    widget=forms.SelectMultiple(attrs={'class':'form-control'}))

    keywords = Keyword.objects.all()
    keyword = forms.ModelMultipleChoiceField(queryset =keywords ,label="Keyword",required=False,
    widget=forms.SelectMultiple(attrs={'class':'form-control'}))
    date = forms.DateTimeField(label="Date",required=False, widget=DateTimeWidget(options=dateTimeOptions, usel10n = True))

class ReachForm(forms.Form):
    dagrs = Dagr.objects.all()
    dagr_id = forms.ModelMultipleChoiceField(queryset=dagrs,label="Choose DAGR ID",required=True,
    widget=forms.SelectMultiple(attrs={'class':'form-control'}))
    ancestors = forms.IntegerField(label="Choose Depth Ancestors", required=False, widget=forms.TextInput(attrs={'class':'form-control'}))
    descendants = forms.IntegerField(label="Choose Depth Descendants", required=False, widget=forms.TextInput(attrs={'class':'form-control'}))


class TimeForm(forms.Form):
    from_date = forms.DateTimeField(label="From Date", widget=DateTimeWidget(options=dateTimeOptions, usel10n = True))
    to = forms.DateTimeField(label="To Date", widget=DateTimeWidget(options=dateTimeOptions, usel10n = True))

dagr2/dagr/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import DagrForm, HtmlParserForm, UploadForm, MetaDataForm, ReachForm, TimeForm, KeywordForm, CategoryForm
from .models import Dagr, Dagr_keywords, Keyword, Category, Relationships
from django.shortcuts import redirect
import datetime
import dateutil.relativedelta
from django.db import connection
from django.db.models import Q
from django.core.exceptions import ValidationError
from django.db import models
import zipfile
from django.views import View
from .html_parser import multi as parse_url
from django.views.decorators.http import require_http_methods
# Create your views here.

def message(request,message=None):
    return render(request, 'dagr/base.html',{'message':message})


# Create your views here.
def index(request):
    return HttpResponse("dummy")


def add_category(request):
    message = None
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            form.save(commit=True)
            message = str(cd['categoryName']) + " Category created"
        else:
            message = "Invalid data"

    form = CategoryForm()

    return render(request, 'dagr/add_manually.html', {'form':form,"message":message})

def add_keyword(request):
    message = None
    if request.method == 'POST':
        form = KeywordForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            form.save(commit=True)
            message = str(cd['name']) + " Keyword created"
        else:
            message="Invalid Keyword"

    form = KeywordForm()

    return render(request, 'dagr/add_manually.html', {'form':form,"message":message})

#add dagr by manually entering the data
def add_manually(request):
    message = None
    if request.method == 'POST':
        form_dagr = DagrForm(request.POST)
        if form_dagr.is_valid():
            try:
                form_dagr.save()
                message = form_dagr.cleaned_data['AssignedName'] + " Saved Successfully"
            except ValidationError as e:
                message = e.message
        else:
            message = "Invalid Input"
            return render(request, 'dagr/add_manually.html',{'form':form_dagr,'message':message})
    else:
        form_dagr = DagrForm()

    return render(request, 'dagr/add_manually.html',{'form':form_dagr,'message':message})

def add_url(request):
    message = None
    if request.method == 'POST':
        form = HtmlParserForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            meta = parse_url(cd['url'])
            try:
                create_dagr_meta(meta)
                message="URL added Successfully"
            except ValidationError as e:
                message = e.message
                return render(request, 'dagr/add_url.html',{'form':form,'message':message})
        else:
            message="Invalid URL"

    form = HtmlParserForm()

    return render(request, 'dagr/add_url.html',{'form':form,'message':message})

def create_dagr_meta(url_meta):
    meta = url_meta[0]
    #change date into valid format
    #example from: 2017-11-01T19:26:16Z to 2017-11-01 19:26
    if (('title' in meta) and len(meta['title']) > 0 ):
        date_created = datetime.datetime.now()
        last_modified = datetime.datetime.now()
        if len(meta["lastmod"]) > 0:
            last_modified = meta['lastmod'].replace("T"," ").replace("Z","")[0:-3]
        if len(meta["pubdate"]) > 0:
            date_created = meta['pubdate'].replace("T"," ").replace("Z","")[0:-3]

        #get or create category
        category, created = Category.objects.get_or_create(categoryName=meta['category'])

        parent = Dagr.objects.create(AssignedName=meta["title"], RealName=meta["title"],Location=meta['location'], LastModified=last_modified, DateCreated=date_created, CategoryID=category, Size=0, Type=meta["doctype"])

        for k in meta['keywords']:
            key_word, created = Keyword.objects.get_or_create(name=k)

            Dagr_keywords.objects.get_or_create(GUID=parent, keyword=key_word)

        #for i in range(1,len(url_meta) ):
        #    if len(url_meta[i]) > 0:
        #        child = create_dagr_meta(url_meta[i])
        #        if child != None:
        #            Relationships.objects.create(ParentGUID=parent.Guid, ChildGUID=child)

        return parent
    else:
        return None

#useful source
#https://docs.djangoproject.com/en/1.11/ref/files/uploads/#module-django.core.files.uploadhandler
def add_file(request):
    count = None
    message = None
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)

        if form.is_valid():
            cd = form.cleaned_data
            #get category of uploaded files
            categ = cd['category']
            #if cd['category']:
            #categ = Category.objects.get(categoryID=cd['category'])

            #loop through all uploaded files
            count  = 0
            for f in cd['documents']:
                #location of current file
                #loc = f.temporary_file_path
                loc = f.name

                #check if uploaded file is a zipfile
                #if zipfile.is_zipfile(f):
                    #handlezipfile(f, categ,loc)
                #else:
                try:
                    dagr = handlefile(f.name, categ, f.size, f.content_type,loc)
                    count = count + 1
                except ValidationError as e:
                    message = f.name + " " + e.message
                    return  render(request, 'dagr/add_file.html',{'form':form,'count':count, 'message':message})

        else:
            message = "Invalid input"

    else:
        form = UploadForm()

    return render(request, 'dagr/add_file.html',{'form':form,'count':count, 'message':message})

#useful link
#https://docs.python.org/3/library/zipfile.html#zipinfo-objects
def handlezipfile(f, categ, loc):
    #create parent dagr form parent directory
    parent = handlefile(f.name, categ, f.size, f.content_type, loc)

    #open and get contents of zip file
    with zipfile.ZipFile(f, "r", zipfile.ZIP_STORED) as openzip:
        filelist = openzip.infolist()
        for child_f in filelist:
            #loc is location of current file
            loc =  str(parent.Location) + "/" + str(parent.AssignedName)
            #if zipfile then handle zip file
            if zipfile.is_zipfile(child_f):
                child = handlezipfile(child_f, categ, loc)
            else:
                child = handlefile(child_f.name, categ, child_f.size, child_f.content_type, loc)

            Relationships.create(ParentGUID=parent.Guid, ChildGUID=child, DateCreated=datetime.datetime.now())
    return parent

#creates a dagr from a file
def handlefile(name, category, siz, content_type, location):
    return Dagr.objects.create(AssignedName=name, RealName=name,Location=location, LastModified=datetime.datetime.now(), DateCreated=datetime.datetime.now(), CategoryID=category, Size=siz, Type=content_type)

def update_dagr(request,guid=None):
    message =  None
    dagr = Dagr.objects.get(Guid=guid)
    if dagr:
        if request.method == 'POST':
            form_dagr = DagrForm(request.POST, instance=dagr)
            if form_dagr.is_valid():
                form_dagr.save()
                message = "Updated Successfully"
                return render(request,'dagr/base.html',{'message':message})
            else:
                message = "Invalid Input " + str(form_dagr.errors)
        form_dagr = DagrForm(instance=dagr)
        form_dagr.fields['RealName'].widget.attrs['readonly'] = True
    else:
        return redirect('dagr:metadata')

    str_guid = str(guid)
    return render(request,'dagr/dagr_update.html',{'message':message,'form':form_dagr,'guid':str_guid })

def delete_dagr(request,guid=None):
    guid = Dagr.objects.get(Guid=guid)
    if guid:
        guid.delete()
        m = "Successfully deleted"
    else:
        m = "Object doesn't Exist"

    return render(request,'dagr/base.html',{'message':m})

#processes metadata queries
def metadata(request,results=None):

    if request.method == 'POST':
        metaForm = MetaDataForm(request.POST)
        print(metaForm['date'])
        if metaForm.is_valid():
            cd = metaForm.cleaned_data
            results = Dagr.objects.all()
            if cd['author']:
                results = results.filter(Author=cd['author'])
            if cd['size']:
                results = results.filter(Size=cd['size'])
            if cd['keyword']:
                key = cd['keyword']
                guids = Dagr_keywords.objects.filter(keyword__in=key)
                results = results.filter(keywords__in=guids)
            if cd['typ']:
                results = results.filter(Type=cd['typ'])
            if cd['date']:
                print(cd['date'])
                results = results.filter(DateCreated=cd['date'])
            if cd['category']:
                results = results.filter(CategoryID__in=cd['category'])
            if cd['name']:
                #Q(income__gte=5000) | Q(income__isnull=True)
                results = results.filter(Q(AssignedName__icontains=cd['name']) | Q(RealName__icontains=cd['name']))
                #results = results.filter()
            if cd['location']:
                results = results.filter(Location=cd['location'])

    else:
        metaForm = MetaDataForm()
        results = None
    return render(request,'dagr/query.html', {'form':metaForm,'results':results})

def reach(request):
    results = None
    if request.method == 'POST':
        form = ReachForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            guid =cd['dagr_id']
            results = list()
            if cd['ancestors']:
                results = guid.get_parents(cd['ancestors'])
            if cd['descendants']:

dagr2/dagr/templates/dagr/add_file.html
{% extends "dagr/base.html" %}

{% block content %}
  <div class="container">
    <div class="row">
      {% if count %}
        <h3>{{count}} file(s) saved</h3>
      {% endif %}
    </div>
  </div>


  <!-- Bulk data entry form -->
  <div class="container">
    <div class="row">
    {% if form %}
      <p><h2>Upload file(s)</h2></p>
      <form action="{% url 'dagr:add_file' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" class="btn btn-primary btn-lg">
      </form>

    {% endif %}
  </div>
  </div>
  {% endblock %}

dagr2/dagr/templates/dagr/add_manually.html
{% extends "dagr/base.html" %}

{% block content %}
<!-- Interface for adding to database -->


<!-- Add a single DAGR manually -->
  <div class="container">
    <div class="row">
      {% if form %}
      <form action="." method="post" class="form">

      {{ form.as_p }}
      {% csrf_token %}
        <!--
        {% for field in form %}
          <div class="form-group">
              {{ field.errors }}
              <label for={{field}}> {{ field.label_tag }} </label>
              {{ field }}
              {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
              {% endif %}
          </div>
        {% endfor %}
        {% csrf_token %}
      -->
      <input type="submit" value="Submit" class="btn btn-primary btn-lg" >
    </form>

<!--
      <p><h2>Add single DAGR manually</h2></p>
      <form action="{% url 'dagr:add_manually' %}" method="post">
        {% csrf_token %}
        {{ form.as_table }}

      </form>
-->
  {% endif %}
    </div>
  </div>






{% endblock %}

dagr2/dagr/templates/dagr/add_url.html
{% extends "dagr/base.html" %}

{% block content %}

  <!-- Html Parser form -->
  <div class="container">
    <div class="row">
      {% if form %}
        <p><h2>HTML Parser</h2></p>
        <form action="." method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Submit" class="btn btn-primary btn-lg">
        </form>
      {% endif %}
    </div>
  </div>
{% endblock %}

dagr2/dagr/templates/dagr/base.html
<!-- base file to be included in every file -->
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet" type="text/css"/>
    <script src="{{ STATIC_URL }}js/bootstrap.js"></script>
    {{ form.media }}

  </head>

  <body>

    <nav class="navbar navbar-light" style="background-color: #2b2944;"">
     <div class="container-fluid">
       <div class="navbar-header">
         <a class="navbar-brand" href="#">DAGR</a>
       </div>
       <ul class="nav navbar-nav">
         <li class="dropdown active">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#"">Data Entry
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <div class="card" style="width: 20rem;">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item btn-block" href="{%url 'dagr:add_manually' %}"> <a class="btn btn-primary" href="{%url 'dagr:add_manually' %}" > Manually Enter metadata </a> </li>
                  <li class="list-group-item btn-block" > <a class="btn btn-primary" href="{%url 'dagr:add_url' %}" > Enter metadata by URL</a> </li>
                  <li class="list-group-item btn-block" > <a class="btn btn-primary" href="{%url 'dagr:add_file' %}" > Enter metadata by File(s)</a> </li>
                  <li class="list-group-item btn-block" > <a class="btn btn-primary" href="{%url 'dagr:add_category' %}" > Add Category </a> </li>
                  <li class="list-group-item btn-block" > <a class="btn btn-primary" href="{%url 'dagr:add_keyword' %}" > Add Keyword </a> </li>
                </ul>
              </div>
              <!-- <li><a href="{%url 'dagr:add_manually' %}">Manually</a></li>
              <li><a href="{%url 'dagr:add_url' %}">URL</a></li>
              <li><a href="{%url 'dagr:add_file' %}">File(s)</a></li> -->
            </ul>
          </li>

         <li><a href="{% url 'dagr:metadata' %}">Metadata Query</a></li>
         <li><a href="{% url 'dagr:reach' %}">Reach Query</a></li>
         <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Time Query
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{%url 'dagr:time' %}">Time Range</a></li>
              <li><a href="{% url 'dagr:time-range' 'yesterday' %}">Yesterday</a></li>
              <li><a href="{% url 'dagr:time-range' 'last_week' %}">Last Week</a></li>
              <li><a href="{% url 'dagr:time-range' 'last_month' %}">Last Month</a></li>
              <li><a href="{% url 'dagr:time-range' 'last_year' %}">Last Year</a></li>
            </ul>
          </li>
          <li class="dropdown">
             <a class="dropdown-toggle" data-toggle="dropdown" href="#">Orphan/Sterile
             <span class="caret"></span></a>
             <ul class="dropdown-menu">
               <li><a href="{% url 'dagr:descendant' 'orphan' %}">Orphan</a></li>
               <li><a href="{% url 'dagr:descendant' 'sterile' %}">Sterile</a></li>
             </ul>
           </li>
       </ul>
     </div>
    </nav>

    {% if message %}
     <div class="container" class="alert alert-primary" role="alert">
        <div class="row">
          <h3>{{ message }}</h3>
        </div>
     </div>
    {% endif %}

    <div class="container" id="content_dagr_add">
      <div class="row">
        {% block content %}
        {% endblock %}
      </div>
    </div>

    {% block javascript %}
    {% endblock %}
  </body>
</html>

dagr2/dagr/templates/dagr/categ_key.html
<!-- Html Parser form -->
<div class="container">
  <div class="row">
    {% if categoryForm %}
      <form action="{% url 'dagr:metadata' %}" method="post">
        {% csrf_token %}
        {{ categoryForm.as_p }}
        <input type="submit" value="Search">
      </form>
    {% endif %}

    {% if categoryForm %}
      <form action="{% url 'dagr:metadata' %}" method="post">
        {% csrf_token %}
        {{ categoryForm.as_p }}
        <input type="submit" value="Search">
      </form>
    {% endif %}
  </div>
  {% endif %}
</div>

dagr2/dagr/templates/dagr/dagr_update.html
<!-- dagr reports and queries -->
{% extends "dagr/base.html" %}

{% block content %}

  <div class="container">
    <div classs="row">
      <h3>Update Dagr</h3>
    </div>
  </div>

  <div class="container">
    <div class="row">
        {% if form %}
          <form action="{% url 'dagr:update_dagr' guid %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p><input type="submit" value="Update" class="btn btn-primary btn-lg"></p>
          </form>
          <a href="{% url 'dagr:delete_dagr' guid %}" class="btn btn-danger btn-lg" role="button">Delete</a>
        {% endif %}
    </div>
  </div>
{% endblock %}

dagr2/dagr/templates/dagr/query.html
<!-- dagr reports and queries -->
{% extends "dagr/base.html" %}

{% block content %}
  <!-- Html Parser form -->
  <div class="container">
    <div class="row">
      {% if form %}
        <form action="{% url 'dagr:metadata' %}" method="post" class="form">
          {{ form.as_p }}
          {% csrf_token %}
          <input type="submit" value="Search" class="btn btn-primary btn-lg">
        </form>
    </div>
    {% endif %}
  </div>

  <div class="container">
    <div class="row">
      {% if results %}
      <table class="table table-striped">
        <thead>
            <tr>
              <th>GUID</th>
              <th>Real Name</th>
              <th>Assigned Name</th>
              <th>Type</th>
              <th>Size</th>
              <th>Author</th>
              <th>Category</th>
              <th>Date Created</th>
            </tr>
        </thead>
        {% for result in results %}
        <tbody>
          <tr>
              <td><a href={{ result.get_absolute_url }}>{{ result.Guid }}</a></td>
              <td>{{ result.RealName}}</td>
              <td>{{ result.AssignedName }}</td>
              <td>{{ result.Type }}</td>
              <td>{{ result.Size }}</td>
              <td>{{ result.Author }}</td>
              <td>{{ result.CategoryID }}</td>
              <td>{{ result.DateCreated }}</td>
          </tr>
        </tbody>
        {% endfor %}
      </table>
      {% endif %}
  </div>
  </div>
{% endblock %}

dagr2/dagr/templates/dagr/reach.html
<!-- dagr reports and queries -->
{% extends "dagr/base.html" %}

{% block content %}
  <!-- Html Parser form -->
  <div class="container">
    <div class="row">
      {% if form %}
        <form action="{% url 'dagr:reach' %}" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Search" class="btn btn-primary btn-lg">
        </form>
    </div>
    {% endif %}
  </div>

  <div class="container">
    <div class="row">
      {% if results %}
      <table class="table table-striped">
        <thead>
            <tr>
              <th>GUID</th>
              <th>Real Name</th>
              <th>Assigned Name</th>
              <th>Type</th>
              <th>Size</th>
              <th>Author</th>
              <th>Category</th>
              <th>Date Created</th>
            </tr>
        </thead>
        {% for result in results %}
        <tbody>
          <tr>
              <td><a href={{ result.get_absolute_url }}>{{ result.Guid }}</a></td>
              <td>{{ result.RealName}}</td>
              <td>{{ result.AssignedName }}</td>
              <td>{{ result.Type }}</td>
              <td>{{ result.Size }}</td>
              <td>{{ result.Author }}</td>
              <td>{{ result.CategoryID }}</td>
              <td>{{ result.DateCreated }}</td>
          </tr>
        </tbody>
        {% endfor %}
      </table>
      {% endif %}
  </div>
  </div>
{% endblock %}

dagr2/dagr/templates/dagr/report.html
<!-- dagr reports and queries -->
{% extends "dagr/base.html" %}

{% block content %}
<div class="container">
  <div class="row">
    {% if results %}

    <table class="table table-striped">
      <thead>
          <tr>
            <th>GUID</th>
            <th>Real Name</th>
            <th>Assigned Name</th>
            <th>Type</th>
            <th>Size</th>
            <th>Author</th>
            <th>Category</th>
            <th>Date Created</th>
            <th>Late Modified</th>
          </tr>
      </thead>
      {% for result in results %}
      <tbody>
        <tr>
            <td><a href={{ result.get_absolute_url }}>{{ result.Guid }}</a></td>
            <td>{{ result.RealName}}</td>
            <td>{{ result.AssignedName }}</td>
            <td>{{ result.Type }}</td>
            <td>{{ result.Size }}</td>
            <td>{{ result.Author }}</td>
            <td>{{ result.CategoryID }}</td>
            <td>{{ result.DateCreated }}</td>
            <td>{{ result.LastModified }}</td>
        </tr>
      </tbody>
      {% endfor %}
    </table>

    {% endif %}
</div>
</div>
{% endblock %}

dagr2/dagr/templates/dagr/time_range.html
<!-- dagr reports and queries -->
{% extends "dagr/base.html" %}

{% block content %}
  <!-- Html Parser form -->
  <div class="container">
    <div class="row">
      {% if form %}
        <form action="{% url 'dagr:time' %}" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Search" class="btn btn-primary btn-lg">
        </form>
    </div>
    {% endif %}
  </div>

  <div class="container">
    <div class="row">
      {% if results %}
      <table class="table table-striped">
        <thead>
            <tr>
              <th>GUID</th>
              <th>Real Name</th>
              <th>Assigned Name</th>
              <th>Type</th>
              <th>Size</th>
              <th>Author</th>
              <th>Category</th>
              <th>Date Created</th>
            </tr>
        </thead>
        {% for result in results %}
        <tbody>
          <tr>
              <td><a href={{ result.get_absolute_url }}>{{ result.Guid }}</a></td>
              <td>{{ result.RealName}}</td>
              <td>{{ result.AssignedName }}</td>
              <td>{{ result.Type }}</td>
              <td>{{ result.Size }}</td>
              <td>{{ result.Author }}</td>
              <td>{{ result.CategoryID }}</td>
              <td>{{ result.DateCreated }}</td>
          </tr>
        </tbody>
        {% endfor %}
      </table>
      {% endif %}
  </div>
  </div>
{% endblock %}